spring:
  application:
    name: gestao
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dbGestao?allowPublicKeyRetrieval=true&useSSL=false&useTimezone=true&serverTimezone=America/Sao_Paulo
    username: user_dca
    password: pwd_dca
    initialization-mode: always
    data: classpath:data.sql
  jpa:
    #    generate-ddl: true
    hibernate:
      ddl-auto: create-drop

